/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package metromendeley;

/**
 *
 * @author USUARIO
 */
public class AnalizeSummary extends javax.swing.JPanel {

    /**
     * Creates new form AnalizeSummary
     */
    public AnalizeSummary() {
        initComponents();
    }
    
    public void setData(Summary getSummary){
        SummaryTitle.setText(getSummary.getTitle());
        String authors="";
        for (int i = 0; i < getSummary.getAuthors().length; i++) {
            authors=authors+getSummary.getAuthors()[i]+"\n";
        }
        authorsSummary.setText(authors);
        String keyW="";
        for (int i = 0; i < getSummary.getKeywordAppearances().length; i++) {
            keyW=keyW+getSummary.getKeywordAppearances()[i]+"\n";
        }
        palabrasClaves.setText(keyW);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSummaries = new javax.swing.JComboBox<>();
        seleccioneResume = new javax.swing.JLabel();
        tituloResumen = new javax.swing.JLabel();
        AutoresdelResumen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keyWordsText = new javax.swing.JTextArea();
        palabrasClaves = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        authorsSummary = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        SummaryTitle = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 204));

        JSummaries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        seleccioneResume.setForeground(new java.awt.Color(0, 0, 0));
        seleccioneResume.setText("Seleccione un resumen");

        tituloResumen.setForeground(new java.awt.Color(0, 0, 0));
        tituloResumen.setText("Título del Resumen");

        AutoresdelResumen.setForeground(new java.awt.Color(0, 0, 0));
        AutoresdelResumen.setText("Autores del Resumen");

        keyWordsText.setColumns(20);
        keyWordsText.setRows(5);
        jScrollPane1.setViewportView(keyWordsText);

        palabrasClaves.setForeground(new java.awt.Color(0, 0, 0));
        palabrasClaves.setText("Palabras Claves:");

        authorsSummary.setColumns(20);
        authorsSummary.setRows(5);
        jScrollPane2.setViewportView(authorsSummary);

        SummaryTitle.setColumns(20);
        SummaryTitle.setRows(5);
        jScrollPane3.setViewportView(SummaryTitle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AutoresdelResumen)
                            .addComponent(tituloResumen)
                            .addComponent(seleccioneResume))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JSummaries, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(palabrasClaves))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSummaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccioneResume))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tituloResumen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoresdelResumen)
                    .addComponent(palabrasClaves))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutoresdelResumen;
    private javax.swing.JComboBox<String> JSummaries;
    private javax.swing.JTextArea SummaryTitle;
    private javax.swing.JTextArea authorsSummary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea keyWordsText;
    private javax.swing.JLabel palabrasClaves;
    private javax.swing.JLabel seleccioneResume;
    private javax.swing.JLabel tituloResumen;
    // End of variables declaration//GEN-END:variables
}
