package metromendeley;

import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class App extends javax.swing.JFrame {
    
    private static final int HASH_TABLE_SIZE = 16;
    
    private final SortedSummaryList summaries = new SortedSummaryList();
    private final HashTable<Summary> summariesByTitle = new HashTable<>(HASH_TABLE_SIZE);
    private final HashTable<List<Summary>> summariesByAuthor = new HashTable<>(HASH_TABLE_SIZE);
    private final HashTable<List<Summary>> summariesByKeyword = new HashTable<>(HASH_TABLE_SIZE);
    
    private File databaseFile = null;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }
    
    public void registerSummary(Summary summary) {
        /* Agregar resumen a la lista */
        summaries.insert(summary);
        /* Agregar resumen a la tabla principal */
        summariesByTitle.set(summary.getTitle().toLowerCase(), summary);
        /* Agregar resumen a la tabla indexada por autores */
        for(String author : summary.getAuthors()) {
            author = author.toLowerCase();
            List<Summary> authorList = summariesByAuthor.get(author);
            if(authorList == null) {
                authorList = new List<>();
                summariesByAuthor.set(author, authorList);
            }
            authorList.append(summary);
        }
        /* Agregar resumen a la tabla indexada por palabras clave */
        for(String keyword : summary.getKeywords()) {
            keyword = keyword.toLowerCase();
            List<Summary> keywordList = summariesByKeyword.get(keyword);
            if(keywordList == null) {
                keywordList = new List<>();
                summariesByKeyword.set(keyword, keywordList);
            }
            keywordList.append(summary);
        }
    }
    
    public void saveState() {
        if(databaseFile != null) {
            try {
                Database.saveState(summaries, databaseFile);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la base de datos", "Error de escritura", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public File getDatabaseFile() {
        return databaseFile;
    }

    public void setDatabaseFile(File databaseFile) {
        this.databaseFile = databaseFile;
    }

    public List<Summary> getSummaries() {
        return summaries;
    }

    public Summary getSummaryByTitle(String title) {
        return summariesByTitle.get(title.toLowerCase());
    }
    
    public List<Summary> getSummariesByAuthor(String author) {
        List<Summary> summaries = summariesByAuthor.get(author.toLowerCase());
        return summaries != null ? summaries : new List<>();
    }
    
    public List<Summary> getSummariesByKeyword(String keyword) {
        List<Summary> summaries =  summariesByKeyword.get(keyword.toLowerCase());
        return summaries != null ? summaries : new List<>();
    }
       
    public void show(String name) {
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, name);
    }
    
    public void showMenu(){
        show("optionsPanel");
    }
    
    public void showAnalyze(){
        analyzeSummaryPanel.updateSummaries(summaries);
        show("analizePanel");
    }
    
    public void showSearchByKeyword(){
        show("searchKey");
    }
    
    public void showSearchByAuthor(){
        show("authorPanel");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        welcomePanel = new metromendeley.WelcomePanel();
        optionsPanel = new metromendeley.OptionsPanel();
        searchAuthorPanel = new metromendeley.SearchAuthorPanel();
        searchKeywordPanel = new metromendeley.SearchKeywordPanel();
        analyzeSummaryPanel = new metromendeley.AnalyzeSummaryPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetroMendeley");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(welcomePanel, "card6");
        mainPanel.add(optionsPanel, "optionsPanel");
        mainPanel.add(searchAuthorPanel, "authorPanel");
        mainPanel.add(searchKeywordPanel, "searchKey");
        mainPanel.add(analyzeSummaryPanel, "analizePanel");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static App instance;
    
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            instance = new App();
            instance.setVisible(true);
        });
    }
    
    public static App getInstance() {
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metromendeley.AnalyzeSummaryPanel analyzeSummaryPanel;
    private javax.swing.JPanel mainPanel;
    private metromendeley.OptionsPanel optionsPanel;
    private metromendeley.SearchAuthorPanel searchAuthorPanel;
    private metromendeley.SearchKeywordPanel searchKeywordPanel;
    private metromendeley.WelcomePanel welcomePanel;
    // End of variables declaration//GEN-END:variables

}

