package metromendeley;

import java.awt.CardLayout;
import java.io.File;

/**
 *
 * @author Andres
 */
public class App extends javax.swing.JFrame {
    
    private static final int HASH_TABLE_SIZE = 16;
    
    private final HashTable<Summary> summariesByTitle = new HashTable<>(HASH_TABLE_SIZE);
    private final HashTable<List<Summary>> summariesByAuthor = new HashTable<>(HASH_TABLE_SIZE);
    private final HashTable<List<Summary>> summariesByKeyword = new HashTable<>(HASH_TABLE_SIZE);
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }
    
    public void registerSummary(Summary summary) {
        /* Agregar resumen a la tabla principal */
        summariesByTitle.set(summary.getTitle(), summary);
        /* Agregar resumen a la tabla indexada por autores */
        for(String author : summary.getAuthors()) {
            List<Summary> authorList = summariesByAuthor.get(author);
            if(authorList == null) {
                authorList = new List<>();
                summariesByAuthor.set(author, authorList);
            }
            authorList.append(summary);
        }
        /* Agregar resumen a la tabla indexada por palabras clave */
        for(String keyword : summary.getKeywords()) {
            List<Summary> keywordList = summariesByKeyword.get(keyword);
            if(keywordList == null) {
                keywordList = new List<>();
                summariesByKeyword.set(keyword, keywordList);
            }
            keywordList.append(summary);
        }
    }
    public void show(String name) {
        ((CardLayout) welcomePanel.getLayout()).show(welcomePanel, name);
    }
    public void showOptions(){
        show("optionPanel");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        textPanel = new metromendeley.textPanel();
        optionsPanel1 = new metromendeley.OptionsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetroMendeley");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        welcomePanel.setLayout(new java.awt.CardLayout());
        welcomePanel.add(textPanel, "textPanel");
        welcomePanel.add(optionsPanel1, "optionPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new App().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metromendeley.OptionsPanel optionsPanel1;
    private metromendeley.textPanel textPanel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
