/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package metromendeley;

/**
 *
 * @author USUARIO
 */
public class OptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        analizeSummary = new javax.swing.JButton();
        searchKey = new javax.swing.JButton();
        searchAuthor = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        seleccionar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        analizeSummary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        analizeSummary.setText("Analizar Resumen");
        analizeSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizeSummaryActionPerformed(evt);
            }
        });
        add(analizeSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 100, 379, -1));

        searchKey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchKey.setText("Buscar por palabra clave");
        searchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKeyActionPerformed(evt);
            }
        });
        add(searchKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 170, 379, -1));

        searchAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchAuthor.setText("Buscar por autor");
        searchAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorActionPerformed(evt);
            }
        });
        add(searchAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 240, 379, -1));

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setText("Cargar nuevo resumen");
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 310, 380, -1));

        seleccionar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        seleccionar.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar.setText("Seleccione una opción");
        add(seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void analizeSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizeSummaryActionPerformed
        App.getInstance().showSearchKey();
    }//GEN-LAST:event_analizeSummaryActionPerformed

    private void searchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKeyActionPerformed
       App.getInstance().showSearchKey();
    }//GEN-LAST:event_searchKeyActionPerformed

    private void searchAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorActionPerformed
        App.getInstance().showSearchAuthor();
    }//GEN-LAST:event_searchAuthorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizeSummary;
    private javax.swing.JButton exit;
    private javax.swing.JButton searchAuthor;
    private javax.swing.JButton searchKey;
    private javax.swing.JLabel seleccionar;
    // End of variables declaration//GEN-END:variables
}
