package metromendeley;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class OptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooser = new javax.swing.JFileChooser();
        titleLabel = new javax.swing.JLabel();
        analizeSummaryButton = new javax.swing.JButton();
        searchKeywordButton = new javax.swing.JButton();
        searchAuthorButton = new javax.swing.JButton();
        loadSummaryButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Seleccione una opción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(titleLabel, gridBagConstraints);

        analizeSummaryButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        analizeSummaryButton.setText("Analizar Resumen");
        analizeSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizeSummaryButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(analizeSummaryButton, gridBagConstraints);

        searchKeywordButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchKeywordButton.setText("Buscar por palabra clave");
        searchKeywordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKeywordButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(searchKeywordButton, gridBagConstraints);

        searchAuthorButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchAuthorButton.setText("Buscar por autor");
        searchAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(searchAuthorButton, gridBagConstraints);

        loadSummaryButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadSummaryButton.setText("Cargar nuevo resumen");
        loadSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSummaryButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.ipadx = 207;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(loadSummaryButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void analizeSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizeSummaryButtonActionPerformed
        //App.getInstance().showOptions();
    }//GEN-LAST:event_analizeSummaryButtonActionPerformed

    private void searchKeywordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKeywordButtonActionPerformed
       App.getInstance().showSearchByKeyword();
    }//GEN-LAST:event_searchKeywordButtonActionPerformed

    private void searchAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorButtonActionPerformed
        App.getInstance().showSearchByAuthor();
    }//GEN-LAST:event_searchAuthorButtonActionPerformed

    private void loadSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSummaryButtonActionPerformed
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try{
                Summary summary = Database.readSummaryTxt(file);
                App.getInstance().registerSummary(summary);
                JOptionPane.showMessageDialog(null, "Carga Exitosa");
            } catch(DuplicateKeyException ex){
                JOptionPane.showMessageDialog(this, "Este resumen ya fue cargado");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No se encontró el archivo", "Archivo no encontrado", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo leer el archivo", "Error de lectura", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error de formato", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_loadSummaryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizeSummaryButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton loadSummaryButton;
    private javax.swing.JButton searchAuthorButton;
    private javax.swing.JButton searchKeywordButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
