/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package metromendeley;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class SearchPanel extends javax.swing.JPanel {
    private static String keyWord;
    private static HashTable<List<Summary>> summaries;
    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introduzcaPalabra = new javax.swing.JLabel();
        getKeyWord = new javax.swing.JTextField();
        investigacionesRelacionadas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSummary = new javax.swing.JTextArea();
        searchKey = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        introduzcaPalabra.setForeground(new java.awt.Color(0, 0, 0));
        introduzcaPalabra.setText("Introduzca la palabra clave");
        add(introduzcaPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 34, -1, -1));

        getKeyWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getKeyWordActionPerformed(evt);
            }
        });
        add(getKeyWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 31, 200, -1));

        investigacionesRelacionadas.setForeground(new java.awt.Color(0, 0, 0));
        investigacionesRelacionadas.setText("Investigaciones relacionadas");
        add(investigacionesRelacionadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 72, -1, -1));

        listSummary.setColumns(20);
        listSummary.setRows(5);
        jScrollPane2.setViewportView(listSummary);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 100, 426, 227));

        searchKey.setText("Buscar");
        searchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKeyActionPerformed(evt);
            }
        });
        add(searchKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void getKeyWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getKeyWordActionPerformed
        
    }//GEN-LAST:event_getKeyWordActionPerformed

    private void searchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKeyActionPerformed
        try{
            keyWord=getKeyWord.getText();
            String summariesString= getSummaries();
            listSummary.setText(summariesString);
        } catch(Exception e){
            JOptionPane.showMessageDialog(getKeyWord, "Introduzca una palabra clave válida");
        }
    }//GEN-LAST:event_searchKeyActionPerformed
    public void setHash(HashTable<List<Summary>> summaries){
        SearchPanel.summaries=summaries;
    }

    public String getSummaries(){
        String summariesString="";
        ListNode<Summary> summaryNode=summaries.get(keyWord).getFirst();
        while(summaryNode!=null){
            summariesString=summariesString+summaries.get(keyWord).getFirst().getValue().getTitle()+"\n";
            summaryNode=summaries.get(keyWord).getFirst().getNext();
        }
        return summariesString;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField getKeyWord;
    private javax.swing.JLabel introduzcaPalabra;
    private javax.swing.JLabel investigacionesRelacionadas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea listSummary;
    private javax.swing.JButton searchKey;
    // End of variables declaration//GEN-END:variables
}
