/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package metromendeley;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class SearchAuthor extends javax.swing.JPanel {
    
    private static String author;
    private static HashTable<List<Summary>> summaries;
    /**
     * Creates new form SearchAuthor
     */
    public SearchAuthor() {
        initComponents();
    }
    
    
    public String getSummaries(){
        String summariesString="";
        ListNode<Summary> summaryNode=summaries.get(author).getFirst();
        while(summaryNode!=null){
            summariesString=summariesString+summaries.get(author).getFirst().getValue().getTitle()+"\n";
            summaryNode=summaries.get(author).getFirst().getNext();
        }
        return summariesString;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingreseNombre = new javax.swing.JLabel();
        getAuthor = new javax.swing.JTextField();
        investigacionesRelacionadas = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        setSummaries = new javax.swing.JTextArea();
        searchAuthor = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        ingreseNombre.setForeground(new java.awt.Color(0, 0, 0));
        ingreseNombre.setText("Introduzca el nombre del autor:");

        investigacionesRelacionadas.setForeground(new java.awt.Color(0, 0, 0));
        investigacionesRelacionadas.setText("Investigaciones relacionadas: ");

        setSummaries.setColumns(20);
        setSummaries.setRows(5);
        scroll.setViewportView(setSummaries);

        searchAuthor.setText("Buscar");
        searchAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(investigacionesRelacionadas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ingreseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchAuthor))
                    .addComponent(scroll))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseNombre)
                    .addComponent(getAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAuthor))
                .addGap(27, 27, 27)
                .addComponent(investigacionesRelacionadas)
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorActionPerformed
        try{
            author=getAuthor.getText();
            String summariesString= getSummaries();
            setSummaries.setText(summariesString);
        } catch(Exception e){
            JOptionPane.showConfirmDialog(this, "Ingrese un autor válido");
        }
    }//GEN-LAST:event_searchAuthorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField getAuthor;
    private javax.swing.JLabel ingreseNombre;
    private javax.swing.JLabel investigacionesRelacionadas;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton searchAuthor;
    private javax.swing.JTextArea setSummaries;
    // End of variables declaration//GEN-END:variables
}
