package metromendeley;

/**
 *
 * @author USUARIO
 */
public class SearchKeywordPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form SearchPanel
     */
    public SearchKeywordPanel() {
        initComponents();
    }
    
    public void setSummaries(String keyword){
        StringBuilder builder = new StringBuilder();
        List<Summary> summaries = App.getInstance().getSummariesByKeyword(keyword);
        for(ListNode<Summary> node = summaries.getFirst(); node != null; node = node.getNext()) {
            builder.append(node.getValue().getTitle()).append("\n");
        }
        relatedSummariesTextArea.setText(builder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        keywordLabel = new javax.swing.JLabel();
        keywordTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        relatedSummariesLabel = new javax.swing.JLabel();
        relatedSummariesScrollPane = new javax.swing.JScrollPane();
        relatedSummariesTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        setLayout(new java.awt.GridBagLayout());

        keywordLabel.setForeground(new java.awt.Color(0, 0, 0));
        keywordLabel.setText("Introduzca la palabra clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        add(keywordLabel, gridBagConstraints);

        keywordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        add(keywordTextField, gridBagConstraints);

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        add(searchButton, gridBagConstraints);

        relatedSummariesLabel.setForeground(new java.awt.Color(0, 0, 0));
        relatedSummariesLabel.setText("Investigaciones relacionadas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        add(relatedSummariesLabel, gridBagConstraints);

        relatedSummariesTextArea.setColumns(20);
        relatedSummariesTextArea.setRows(5);
        relatedSummariesScrollPane.setViewportView(relatedSummariesTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(relatedSummariesScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void keywordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTextFieldActionPerformed
        setSummaries(keywordTextField.getText());
    }//GEN-LAST:event_keywordTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        setSummaries(keywordTextField.getText());
    }//GEN-LAST:event_searchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextField keywordTextField;
    private javax.swing.JLabel relatedSummariesLabel;
    private javax.swing.JScrollPane relatedSummariesScrollPane;
    private javax.swing.JTextArea relatedSummariesTextArea;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
