/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package metromendeley;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class textPanel extends javax.swing.JPanel {
    private File selectFile;
    /**
     * Creates new form textPanel
     */
    public textPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        welcome = new javax.swing.JLabel();
        chargeTxt = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 0, 0));
        welcome.setText("BIENVENIDOS A METROMENDELEY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(170, 60, 0, 60);
        add(welcome, gridBagConstraints);

        chargeTxt.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        chargeTxt.setText("Cargar archivo de texto");
        chargeTxt.setAlignmentY(0.0F);
        chargeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 80, 168, 0);
        add(chargeTxt, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void chargeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeTxtActionPerformed
       JFileChooser fileChooser= new JFileChooser();
       if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Carga Exitosa");
       }
    }//GEN-LAST:event_chargeTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chargeTxt;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
