/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package metromendeley;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class textPanel extends javax.swing.JPanel {
    private File selectFile;
    /**
     * Creates new form textPanel
     */
    public textPanel() {
        initComponents();
        loadTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        chargeTxt = new javax.swing.JButton();
        loadTxt = new javax.swing.JButton();
        ejecucionAnterior = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 0, 0));
        welcome.setText("BIENVENIDOS A METROMENDELEY");
        add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 450, -1));

        chargeTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chargeTxt.setText("Seleccionar nuevo resumen");
        chargeTxt.setAlignmentY(0.0F);
        chargeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeTxtActionPerformed(evt);
            }
        });
        add(chargeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, -1));

        loadTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadTxt.setText("Cargar Resumen");
        loadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTxtActionPerformed(evt);
            }
        });
        add(loadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 170, -1));

        ejecucionAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ejecucionAnterior.setText("Cargar Resumenes anteriores");
        ejecucionAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecucionAnteriorActionPerformed(evt);
            }
        });
        add(ejecucionAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 360, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void chargeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeTxtActionPerformed
       JFileChooser fileChooser= new JFileChooser();
       if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectFile = fileChooser.getSelectedFile();
            loadTxt.setEnabled(true);
       }
    }//GEN-LAST:event_chargeTxtActionPerformed

    private void loadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTxtActionPerformed
        if(selectFile!=null){
           App.getInstance().loadTxt(selectFile); 
        }
    }//GEN-LAST:event_loadTxtActionPerformed

    private void ejecucionAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecucionAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecucionAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chargeTxt;
    private javax.swing.JButton ejecucionAnterior;
    private javax.swing.JButton loadTxt;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
