package metromendeley;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class WelcomePanel extends javax.swing.JPanel {
    private File selectedFile;
    /**
     * Creates new form textPanel
     */
    public WelcomePanel() {
        initComponents();
        loadTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        welcome = new javax.swing.JLabel();
        chargeTxt = new javax.swing.JButton();
        loadTxt = new javax.swing.JButton();
        ejecucionAnterior = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 0, 0));
        welcome.setText("BIENVENIDOS A METROMENDELEY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(welcome, gridBagConstraints);

        chargeTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chargeTxt.setText("Seleccionar nuevo resumen");
        chargeTxt.setAlignmentY(0.0F);
        chargeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(chargeTxt, gridBagConstraints);

        loadTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadTxt.setText("Cargar Resumen");
        loadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(loadTxt, gridBagConstraints);

        ejecucionAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ejecucionAnterior.setText("Cargar Resumenes anteriores");
        ejecucionAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecucionAnteriorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(ejecucionAnterior, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void chargeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeTxtActionPerformed
       JFileChooser fileChooser= new JFileChooser();
       if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            loadTxt.setEnabled(true);
       }
    }//GEN-LAST:event_chargeTxtActionPerformed

    private void loadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTxtActionPerformed
        try{
            Summary summary = Database.readSummaryTxt(selectedFile);
            App.getInstance().registerSummary(summary);
            JOptionPane.showMessageDialog(null, "Carga Exitosa");
        } catch(DuplicateKeyException ex){
            JOptionPane.showMessageDialog(this, "Este resumen ya fue cargado");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se encontrï¿½ el archivo", "Archivo no encontrado", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo leer el archivo", "Error de lectura", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Error de formato", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_loadTxtActionPerformed

    private void ejecucionAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecucionAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecucionAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chargeTxt;
    private javax.swing.JButton ejecucionAnterior;
    private javax.swing.JButton loadTxt;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
